from django.urls import path
from .views import (
    LoginAPIView,
    RegisterAPIView,
    PortfolioListAPIView,
    SectorPortfolioListAPIView,
    AddStockAPIView,
    StockListAPIView,
    StockPreviewAPIView,
    MultiStockHistoryAPIView,
    PortfolioStockDetailAPIView,
    StockPredictionAPIView,
    StockClusteringAPIView,
    PortfolioGrowthAPIView, # Added PortfolioGrowthAPIView
    Nifty50PCAAPIView,
    PreciousMetalsAPIView,
    CryptoForecastingAPIView,
    StockSearchAPIView,
    ModelBacktestAPIView,
    DeletePortfolioStockAPIView,
    SentimentAPIView,
    AIReviewView,
)

urlpatterns = [
    path('login/', LoginAPIView.as_view()),
    path('register/', RegisterAPIView.as_view()),
    path('portfolios/', PortfolioListAPIView.as_view()),
    path('sector-portfolios/', SectorPortfolioListAPIView.as_view()),
    path('portfolio/<int:portfolio_id>/stocks/', StockListAPIView.as_view()),
    path('sentiment/', SentimentAPIView.as_view()),
    path('ai-review/', AIReviewView.as_view()),
    path('add-stock/', AddStockAPIView.as_view()),
    path('portfolio-stocks/', StockListAPIView.as_view()),
    path('portfolio-stocks/<int:pk>/', PortfolioStockDetailAPIView.as_view()),
    path('stock-preview/', StockPreviewAPIView.as_view()),
    path('stock-search/', StockSearchAPIView.as_view()),
    path('portfolio-history/', MultiStockHistoryAPIView.as_view()),
    path('stock-prediction/', StockPredictionAPIView.as_view()),
    path('stock-clustering/', StockClusteringAPIView.as_view()),
    path('portfolio-growth/', PortfolioGrowthAPIView.as_view()), # Registered PortfolioGrowthAPIView
    path('nifty50-pca/', Nifty50PCAAPIView.as_view()),
    path('precious-metals/', PreciousMetalsAPIView.as_view()),
    path('crypto-ai/', CryptoForecastingAPIView.as_view()),
    path('backtest/', ModelBacktestAPIView.as_view()),
    path('portfolio/delete-stock/', DeletePortfolioStockAPIView.as_view()),
]