# Generated by Django 6.0.2 on 2026-03-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliostock',
            name='discount_level',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfoliostock',
            name='opportunity',
            field=models.FloatField(default=0),
        ),
    ]
