# Generated by Django 6.0.2 on 2026-03-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_sector_alter_portfoliostock_discount_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostock',
            name='max_price',
            field=models.FloatField(default=0),
        ),
    ]
