# Generated by Django 6.0.2 on 2026-03-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_portfoliostock_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliostock',
            name='max_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliostock',
            name='pe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
